<div class="jumbotron">
    <h1>Administrace &ndash; <span class="zf-green">Uložená data</span></h1>
    <p>
        Zde je přehled dat uložených <strong>Hypotéční kalkulačkou</strong>. V současnosti je uloženo <strong style="color: #f30;">1556</strong> záznamů.
    </p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>
                    <strong style="color: #f30;">XXX</strong> &ndash; Vložit <code>DataTable</code>!
                </p>
            </div>
        </div>
    </div>
</div>