<div class="jumbotron">
    <h1><a href="<?php echo $this->url('admin') ?>">Administrace</a> &ndash; <span class="zf-green">Cílové servery</span></h1>
    <p>
        V této části můžete nastavit cílové servery na kterých je <strong>Hypotéční kalkulačka</strong> zobrazena. Aktuálně máte definovaných <strong style="color: #f30;">6</strong> destinací.
    </p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>
                    <strong style="color: #f30;">XXX</strong> &ndash; Vložit <code>DestinationForm</code> a <code>DestinationsTable</code>!
                </p>
            </div>
        </div>
    </div>
</div>