<div class="row">
<pre>
Potřebuji naprogramovat hypoteční kalkulačku. Která bude obsahovat 4 druhy 
fixace a v nich 3 povolená pásma. Splatnost 5 - 30 let.
 _____________________ 
|    <strong>Fixace 1 rok</strong>     |
|---------------------|
| Do 85% | akt. 1,54% |
| Do 90% | akt. 2,24% |
| Do 95% | 3,29 %     |
|---------------------|
|    <strong>Fixace 3/5 let</strong>   |
|---------------------|
| Do 85% | akt. 1,54% |
| Do 90% | akt. 1,89% |
| Do 95% | 2,49 %     |
|---------------------|
|    <strong>Fixace 10 let</strong>    |
|---------------------|
| Do 85% | akt. 1,83% |
| Do 90% | akt. 2,19% |
| Do 95% | 2,89 %     |
|________|____________|

Procenta u jednotlivých sazeb se budou průběžně měnit (ideální nějaký vstup, 
který bude mít oddělený konfigurační soubor).

<strong>Základní specifikace</strong>
- kalkulačka by měla vycházet z webu: <a href="https://www.gpf.cz/hypotecni-kalkulacka/onepage">https://www.gpf.cz/hypotecni-kalkulacka/onepage</a>, 
  s tím rozdílem, že se nebudou porovnávat nabídky, ale bude zde jen <em>Spočítat splátku</em>;
- následně by se zobrazila jen jedna nabídka, jako 4 HYPOTÉKA, s možností 
  měnit: viz. uvedená kalkulačka a pod ní kontaktní formulář, který se odešle 
  na stanovený email;
- kalkulačka by měla být postavená tak, aby bylo možné ji vkládat na ruzné weby 
  pomocí iframe kódu.
</pre>
</div>

<div class="jumbotron">
    <h1>Administrace <span class="zf-green">Hypotéčení kalkulačky</span></h1>
    <p>
        <strong>Hypotéční kalkulačka</strong> je úspěšně nainstalována a probíhá sběr dat. V současnosti je uloženo <strong style="color: #f30;">1556</strong> záznamů.
    </p>
    <p class="text-right">
        <a class="btn btn-primary btn-lg" href="<?php echo $this->url( 'admin/data' ) ?>">Zobrazit shromážděná data &raquo;</a>&nbsp;
    </p>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Cílové servery</h3>
            </div>
            <div class="panel-body">
                <p>
                    V této části můžete nastavit cílové servery na kterých je <strong>Hypotéční kalkulačka</strong> zobrazena. Aktuálně máte definovaných <strong style="color: #f30;">6</strong> destinací.
                </p>
                <p>
                    <a class="btn btn-danger pull-right" href="<?php echo $this->url( 'admin/destinations' ) ?>">Nastavit cílové servery &raquo;</a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Nastavení aplikace</h3>
            </div>
            <div class="panel-body">
                <p>
                    Zde můžete upravit další nastavení aplikace <strong>Hypotéční kalkulačka</strong> &ndash; jako jsou notifikační emaily, přístup k databázi atp.
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="<?php echo $this->url( 'admin/settings' ) ?>">Upravit nastavení &raquo;</a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Nápověda &amp; Podpora</h3>
            </div>
            <div class="panel-body">
                <p>
                    Pokud potřebujete pomoc či si chcete objednat úpravy napište zpravu na email <a href="mailto:ondrejd@gmail.com">ondrejd@gmail.com</a> autorovi této aplikace.
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="https://github.com/ondrejd/hypotecni-kalkulacka" target="_blank">Stránky projektu &raquo;</a>
                </p>
            </div>
        </div>
    </div>
</div>