<div class="jumbotron">
    <h1>Administrace &ndash; <span class="zf-green">Nastavení</span></h1>
    <p>
        Zde můžete upravit další nastavení aplikace <strong>Hypotéční kalkulačka</strong> &ndash; jako jsou notifikační emaily, přístup k databázi atp.
    </p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Nastavení aplikace <span>Hypotéční kalkulačka</span></h3>
            </div>
            <div class="panel-body">
                <div class="form">
                    <?php
                    /**
                     * @var \Application\Form\SettingsForm $form
                     */
                    $form = $this->settingsForm;
                    $form->prepare();

                    echo $this->form()->openTag($form);
                    echo $this->formElement($form->get('security'));
                    ?>
                    <?php echo $this->form()->openTag( $form ) ?>
                    <div class="form-group">
                    <div class="form-group">
                        <?php echo $this->formRow($form->get('email')) ?>
                        <p class="small"><?php echo $form->get('email')->getOption('description'); ?></p>
                    </div>
                    <div class="form-group">
                        <label><?php
                            $confirmations = $form->get('confirmations');
                            echo $this->formInput($confirmations);
                            echo $confirmations->getOption('label');
                        ?></label>
                        <p class="small"><?php echo $confirmations->getOption('description'); ?></p>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formSubmit($form->get('send')) ?>
                    </div>
                    <?php echo $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
    </div>
</div>