<div class="jumbotron">
    <h1>Administrace &ndash; <span class="zf-green">Nastavení</span></h1>
    <p>
        Zde můžete upravit další nastavení aplikace <strong>Hypotéční kalkulačka</strong> &ndash; jako jsou notifikační emaily, přístup k databázi atp.
    </p>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>
                    <strong style="color: #f30;">XXX</strong> &ndash; Vložit <code>SettingsForm</code>!
                </p>
            </div>
        </div>
    </div>
</div>