<pre>
Potřebuji naprogramovat hypoteční kalkulačku. Která bude obsahovat 4 druhy 
fixace a v nich 3 povolená pásma. Splatnost 5 - 30 let.
 _____________________ 
|    <strong>Fixace 1 rok</strong>     |
|---------------------|
| Do 85% | akt. 1,54% |
| Do 90% | akt. 2,24% |
| Do 95% | 3,29 %     |
|---------------------|
|    <strong>Fixace 3/5 let</strong>   |
|---------------------|
| Do 85% | akt. 1,54% |
| Do 90% | akt. 1,89% |
| Do 95% | 2,49 %     |
|---------------------|
|    <strong>Fixace 10 let</strong>    |
|---------------------|
| Do 85% | akt. 1,83% |
| Do 90% | akt. 2,19% |
| Do 95% | 2,89 %     |
|________|____________|

Procenta u jednotlivých sazeb se budou průběžně měnit (ideální nějaký vstup, 
který bude mít oddělený konfigurační soubor).

<strong>Základní specifikace</strong>
- kalkulačka by měla vycházet z webu: <a href="https://www.gpf.cz/hypotecni-kalkulacka/onepage">https://www.gpf.cz/hypotecni-kalkulacka/onepage</a>, 
  s tím rozdílem, že se nebudou porovnávat nabídky, ale bude zde jen <em>Spočítat splátku</em>;
- následně by se zobrazila jen jedna nabídka, jako 4 HYPOTÉKA, s možností 
  měnit: viz. uvedená kalkulačka a pod ní kontaktní formulář, který se odešle 
  na stanovený email;
- kalkulačka by měla být postavená tak, aby bylo možné ji vkládat na ruzné weby 
  pomocí iframe kódu.
</pre>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Hypotéční kalkulačka - krok 1</h3>
            </div>
            <div class="panel-body">
                <p>...</p>
                <div class="form-container">
                    <?php
                    /**
                     * @var \Application\Form\CalendarForm $form
                     */
                    $form = $this->calculatorForm;
                    $form->prepare();

                    echo $this->form()->openTag($form);
                    echo $this->formElement($form->get('security'));

                    $input_price     = $form->get('estate_price');
                    $input_mortgage  = $form->get('mortgage');
                    $input_amort     = $form->get('amortization_length');
                    $input_fixation  = $form->get('fixation');
                    $input_assurance = $form->get('assurance');
                    ?>
                    <div class="form-group">
                        <label for="<?= $input_price->getAttribute('id') ?>"><?= $input_price->getOption('label') ?></label>
                        <?= $this->formElement($input_price) ?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_mortgage->getAttribute('id') ?>"><?= $input_mortgage->getOption('label') ?></label>
                        <?= $this->formElement($input_mortgage) ?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_amort->getAttribute('id') ?>"><?= $input_amort->getOption('label') ?></label>
                        <?= $this->formElement($input_amort) ?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_fixation->getAttribute('id') ?>"><?= $input_fixation->getOption('label') ?></label>
                        <?= $this->formElement($input_fixation) ?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_assurance->getAttribute('id') ?>">
                            <?= $this->formElement($input_assurance) ?>
                            <?= $input_assurance->getOption('label') ?>
                        </label>
                    </div>
                    <div class="form-group">
                        <?= $this->formSubmit($form->get('send')) ?>
                    </div>
                    <?= $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Pomůžeme vám získat nejvýhodnější hypotéku</h3>
            </div>
            <div class="panel-body">
                <p>Vyplňte kontaktní informace a sejděte se s naším makléřem ve vaší lokalitě, pomůže vám vyjednat ty nejlepší podmínky. Všechny naše služby jsou zdarma.</p>
                <div class="form-container">
                    <?php
                    /**
                     * @var \Application\Form\ContactForm $form
                     */
                    $form = $this->contactForm;
                    $form->prepare();

                    echo $this->form()->openTag($form);
                    echo $this->formElement($form->get('security'));

                    $input_name = $form->get('name');
                    $input_email = $form->get('email');
                    $input_phone = $form->get('phone');
                    $input_zip = $form->get('zip');
                    ?>
                    <div class="form-group">
                        <label for="<?= $input_name->getAttribute('id') ?>"><?= $input_name->getOption('label') ?></label>
                        <?= $this->formElement($input_name) ?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_email->getAttribute('id') ?>"><?= $input_email->getOption('label') ?></label>
                        <?= $this->formElement($input_email) ?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_phone->getAttribute('id') ?>"><?= $input_phone->getOption('label') ?></label>
                        <?= $this->formElement($input_phone);?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_zip->getAttribute('id') ?>"><?= $input_zip->getOption('label') ?></label>
                        <?= $this->formElement($input_zip);?>
                    </div>
                    <div class="form-group">
                        <?= $this->formSubmit($form->get('send')) ?>
                    </div>
                    <?= $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
    </div>
</div>