<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Hypotéční kalkulačka - krok 1</h3>
            </div>
            <div class="panel-body">
                <p>...</p>
                <div class="form-container">
                    <?php
                    /**
                     * @var \Application\Form\CalendarForm $form
                     */
                    $form = $this->calculatorForm;
                    $form->prepare();

                    echo $this->form()->openTag($form);
                    echo $this->formElement($form->get('security'));

                    $input_price     = $form->get('estate_price');
                    $input_mortgage  = $form->get('mortgage');
                    $input_amort     = $form->get('amortization_length');
                    $input_fixation  = $form->get('fixation');
                    $input_assurance = $form->get('assurance');
                    ?>
                    <div class="form-group">
                        <label for="<?= $input_price->getAttribute('id') ?>"><?= $input_price->getOption('label') ?></label>
                        <?= $this->formElement($input_price) ?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_mortgage->getAttribute('id') ?>"><?= $input_mortgage->getOption('label') ?></label>
                        <?= $this->formElement($input_mortgage) ?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_amort->getAttribute('id') ?>"><?= $input_amort->getOption('label') ?></label>
                        <?= $this->formElement($input_amort) ?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_fixation->getAttribute('id') ?>"><?= $input_fixation->getOption('label') ?></label>
                        <?= $this->formElement($input_fixation) ?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_assurance->getAttribute('id') ?>">
                            <?= $this->formElement($input_assurance) ?>
                            <?= $input_assurance->getOption('label') ?>
                        </label>
                    </div>
                    <div class="form-group">
                        <?= $this->formSubmit($form->get('send')) ?>
                    </div>
                    <?= $this->form()->closeTag() ?>
                </div>
                <script type="text/javascript">
jQuery(".input-mortgage,.input-estate_price").slider({
    formatter: function(value) {
		return new Number(value).toLocaleString() + " Kč";
	}
});
jQuery(".input-amortization_length").slider({
    formatter: function(value) {
        if (value == 1) {
            return "1 rok";
        }
        else if (value > 1 && value < 5) {
            return value + " roky";
        }
        else {
            return value + " let";
        }
	}
});
                </script>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Pomůžeme vám získat nejvýhodnější hypotéku</h3>
            </div>
            <div class="panel-body">
                <p>Vyplňte kontaktní informace a sejděte se s naším makléřem ve vaší lokalitě, pomůže vám vyjednat ty nejlepší podmínky. Všechny naše služby jsou zdarma.</p>
                <div class="form-container">
                    <?php
                    /**
                     * @var \Application\Form\ContactForm $form
                     */
                    $form = $this->contactForm;
                    $form->prepare();

                    echo $this->form()->openTag($form);
                    echo $this->formElement($form->get('security'));

                    $input_name = $form->get('name');
                    $input_email = $form->get('email');
                    $input_phone = $form->get('phone');
                    $input_zip = $form->get('zip');
                    ?>
                    <div class="form-group">
                        <label for="<?= $input_name->getAttribute('id') ?>"><?= $input_name->getOption('label') ?></label>
                        <?= $this->formElement($input_name) ?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_email->getAttribute('id') ?>"><?= $input_email->getOption('label') ?></label>
                        <?= $this->formElement($input_email) ?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_phone->getAttribute('id') ?>"><?= $input_phone->getOption('label') ?></label>
                        <?= $this->formElement($input_phone);?>
                    </div>
                    <div class="form-group">
                        <label for="<?= $input_zip->getAttribute('id') ?>"><?= $input_zip->getOption('label') ?></label>
                        <?= $this->formElement($input_zip);?>
                    </div>
                    <div class="form-group">
                        <?= $this->formSubmit($form->get('send')) ?>
                    </div>
                    <?= $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
    </div>
</div>